# .github/workflows/release.yml

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: cli-speedtest
            asset_name: speedtest-linux-amd64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: cli-speedtest.exe
            asset_name: speedtest-windows-amd64.exe

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: cli-speedtest
            asset_name: speedtest-macos-intel

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: cli-speedtest
            asset_name: speedtest-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Release Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Generate Checksum (Non-Windows)
        if: matrix.os != 'windows-latest'
        run: shasum -a 256 target/${{ matrix.target }}/release/${{ matrix.artifact_name }} | cut -d' ' -f1 > target/${{ matrix.target }}/release/${{ matrix.artifact_name }}.sha256

      - name: Generate Checksum (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $hash = (Get-FileHash target/${{ matrix.target }}/release/${{ matrix.artifact_name }} -Algorithm SHA256).Hash.ToLower()
          Set-Content -Path target/${{ matrix.target }}/release/${{ matrix.artifact_name }}.sha256 -Value $hash

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload checksums to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}.sha256
          asset_name: ${{ matrix.asset_name }}.sha256
          tag: ${{ github.ref }}
          overwrite: true
